const types = {
    GET_SALAO: '@salao/GET',
    UPDATE_SALAO: '@salao/UPDATE',
    ALL_SERVICOS: '@salao/GET',
    UPDATE_SERVICOS: '@salao/UPDATE_SERVICOS',
    UPDATE_AGENDAMENTO: '@salao/UPDATE_AGENDAMENTO',
    UPDATE_FORM: '@salao/UPDATE_FORM',
    FILTER_AGENDA: '@salao/FILTER_AGENDA',
    UPDATE_AGENDA: '@salao/UPDATE_AGENDA',
    UPDATE_COLABORADORES: '@salao/UPDATE_COLABORADORES',
    RESET_AGENDAMENTO: '@salao/RESET_AGENDAMENTO',
    SAVE_AGENDAMENTO: '@salao/SAVE_AGENDAMENTO',
    CLOSE_AGENDAMENTO:'@salao/CLOSE_AGENDAMENTO',
    UPDATE_CLIENTE_ID:'@salao/UPDATE_CLIENTE_ID',
    SET_CLIENTE_ID:'@salao/SET_CLIENTE_ID',
    GET_CLIENTE:'@salao/GET_CLIENTE',
    UPDATE_CLIENTE:'@salao/UPDATE_CLIENTE',
    
    GET_AGENDA_CLIENTE:'@salao/GET_AGENDA_CLIENTE',
    UPDATE_AGENDA_CLIENTE:'@salao/UPDATE_AGENDA_CLIENTE'
};
    
export default types;
